### PR TITLE
SIWPA-8: API - Modify Listing Routes

### PR DESCRIPTION
**Pull request by jventura1738**
### Modified listing routes to include a list of corresponding tags (if any; empty list otherwise).

Tested on my own, now just need some tests from the team.  Access the routes (ex: http://localhost:5000/get-listings/active) and check it against the seeded database to be sure the appropriate tags appear.

@jacobduncan00: let me know if you're okay with the payload format.  Also, not sure whats up with the <code>package-lock.json</code> file.

### CODE REVIEW

**Comment by jacobduncan00** [comment]
✅ Looks good to me and the payload layout is fine with me

**Comment by jacobduncan00** [comment]
Yeah i'm not sure, your PR last time deleted from package-lock.json too idk whats going on with that

**Comment by jacobduncan00** [comment]
https://github.com/npm/cli/issues/4263

**Comment by megfinnegan** [comment]
✅

**Pull request merged**
