### PR TITLE
SIWPA-22 Create and Apply Status Codes to API

### PR DESCRIPTION
**Pull request by jventura1738**
Need all to double check that I did not miss any, and used correct codes :) Thanks

### CODE REVIEW

**Comment by jacobduncan00** [comment]
✅

**Comment by jacobduncan00** [comment]
@Blaine-Mason @megfinnegan Please look at this when you get a chance so we can get it merged

**Comment by megfinnegan** [comment]
✅

**Comment by Blaine-Mason** [comment]
✅

**Pull request merged**
